apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app3
spec:
  selector:
    matchLabels:
      app: nginx-app3
  template:
    metadata:
      labels:
        app: nginx-app3
    spec:
      containers:
      - name: nginx-app3
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
