apiVersion: v1
kind: Pod
metadata:
  name: linux
  namespace: default
  labels:
    name: linux
spec:
  containers:
    - name: busy-box
      image: busybox
      command:
        - sleep
        - '3600'
      resources:
        limits:
          memory: 128Mi
          cpu: 50m
    - name: alpine
      image: alpine:3.2
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
      command:
        - /bin/sh
        - '-c'
        - 'sleep 60m'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
