
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app01
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec: 
  destination: 
    namespace: multi-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: k8s/app-of-app-argocd/app-1
    repoURL: "https://github.com/arsom/gitops-argocd.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true