apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app-of-app
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: 'https://github.com/arsom/gitops-argocd.git'
    path: argocd/app-of-app
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
