services:
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1234
    ports:
      - 8880:80
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - /mnt/d/Personal/mount/mysql:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8888:80

networks:
  workpress:
    driver: bridge